# 配置文件


loveMsg:

  start_stamp: 2023-01-01

  city_name: 东莞

  girl_name: 

  boy_name: 

  card_url: https://api.vvhan.com/api/60s
  # 天气生活指数提示（默认开启）
  weather_tips: true
  # 极端天气温度提醒（默认开启）
  # 卡片内容字节限制可能显示不完全
  weather_tem: true
  # 农历信息（默认开启）
  date_lunarInfo: false
